

# Лабораторная работа 3.2. Знакомство с NumPy
Библиотека NumPy -- быстрая библиотека для математики в Python, основная структура данных -- массив `numpy.array`:

![](https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif)

In [ ]:
# подключение модуля numpy под именем np
import numpy as np

In [ ]:
# основная структура данных - массив
a = np.array([1, 2, 3, 4, 5])
b = np.array([0.1, 0.2, 0.3, 0.4, 0.5])

print("a =", a)
print("b =", b)

Создайте массив с 5 любыми числами:

In [3]:
import numpy as np
mas = np.array([1, 9, 8, 4, 3])
print(mas)

[1 9 8 4 3]


Арифметические операции, в отличие от операций над списками, применяются поэлементно:

In [4]:
list1 = [1, 2, 3]
array1 = np.array([1, 2, 3])

print("list1:", list1)
print('\tlist1 * 3:', list1 * 3)
print('\tlist1 + [1]:', list1 + [1])

print('array1:', array1)
print('\tarray1 * 3:', array1 * 3)
print('\tarray1 + 1:', array1 + 1)

list1: [1, 2, 3]
	list1 * 3: [1, 2, 3, 1, 2, 3, 1, 2, 3]
	list1 + [1]: [1, 2, 3, 1]
array1: [1 2 3]
	array1 * 3: [3 6 9]
	array1 + 1: [2 3 4]


Создайте массив из 5 чисел. Возведите каждый элемент массива в степень 3

In [8]:
#YOUR CODEimport numpy as np
mas = np.array([1, 9, 8, 4, 3])
print(f'mas = {mas}')
print(f'mas^3 = {(mas * mas * mas)}')

mas = [1 9 8 4 3]
mas^3 = [  1 729 512  64  27]


Если в операции участвуют $2$ массива (по умолчанию -- одинакового размера), операции считаются для соответствующих пар:

In [9]:
print("a + b =", a + b)
print("a * b =", a * b)

NameError: name 'a' is not defined

In [ ]:
# вот это разность
print("a - b =", a - b)

# вот это деление
print("a / b =", a / b)

# вот это целочисленное деление
print("a // b =", a // b)

# вот это квадрат
print("a ** 2 =", a ** 2)

 Создайте два массива одинаковой длины. Выведите массив, полученный делением одного массива на другой.

In [11]:
mas_1 = np.array([2, 4, 6, 8, 10])
mas_2 = np.array([1, 2, 3, 4, 5])
print(mas_1 // mas_2)

[2 2 2 2 2]


#### *Л — логика*
К элементам массива можно применять логические операции.

Возвращаемое значение -- массив, содержащий результаты вычислений для каждого элемента (`True` -- "да" или `False` -- "нет"):

In [ ]:
print("a =", a)
print("\ta > 1: ", a > 1)
print("\nb =", b)
print("\tb < 0.5:  ", b < 0.5)

print("\nОдновременная проверка условий:")
print("\t(a > 1) & (b < 0.5):  ", (a>1) & (b < 0.5))
print("А вот это проверяет, что a > 1 ИЛИ b < 0.5:  ", (a > 1) | (b < 0.5))

Создайте 2 массива из 5 элементов. Проверьте условие "Элементы первого массива меньше 6, элементы второго массива делятся на 3"

In [15]:
import numpy as np
a = np.array([1, 2, 3, 6, 7])
b = np.array([3, 6, 8, 11, 15])
print('a < 6 = ', a < 6)
print('b % 3 = ', b % 3 == 0)

a < 6 =  [ True  True  True False False]
b % 3 =  [ True  True False False  True]


Теперь проверьте условие "Элементы первого массива делятся на 2 или элементы второго массива больше 2"

In [16]:
import numpy as np
a = np.array([1, 2, 3, 6, 7])
b = np.array([3, 6, 8, 11, 15])
print('a%2==0 OR b>2 - ', (a % 2 == 0) | (b > 2))

a%2==0 OR b>2 -  [ True  True  True  True  True]


Зачем это нужно? Чтобы выбирать элементы массива, удовлетворяющие какому-нибудь условию:

In [ ]:
print("a =", a)
print("a > 2:", a > 2)
# индексация - выбираем элементы из массива в тех позициях, где True
print("a[a > 2]:", a[a > 2])

Создайте массив с элементами от 1 до 20. Выведите все элементы, которые больше 5 и не делятся на 2

Подсказка: создать массив можно с помощью функции np.arange(), действие которой аналогично функции range, которую вы уже знаете.

In [20]:
import numpy as np
mas = np.arange(1, 21)
print(mas[(mas>5)&(mas%2!=0)])

[ 7  9 11 13 15 17 19]


#### А ещё NumPy умеет...

Все операции NumPy оптимизированы для быстрых вычислений над целыми массивами чисел и в методах `np.array` реализовано множество функций, которые могут вам понадобиться:

In [ ]:
# теперь можно считать средний размер котиков в одну строку!
print("np.mean(a) =", np.mean(a))
# минимальный элемент
print("np.min(a) =", np.min(a))
# индекс минимального элемента
print("np.argmin(a) =", np.argmin(a))
# вывести значения массива без дубликатов
print("np.unique(['male', 'male', 'female', 'female', 'male']) =", np.unique(['male', 'male', 'female', 'female', 'male']))

# и ещё много всяких методов
# Google в помощь

---

---

Пора еще немного потренироваться с NumPy.

Выполните операции, перечисленные ниже:

In [23]:
import numpy as np
a = np.array([1, 4, 6, 2, 10])
b = np.array([2, 3, 9, 5, 12])

print("Разность между a и b:", a - b
     )
print("Квадраты элементов b:", b*b
     )
print("Половины произведений элементов массивов a и b:", a * b // 2
     )

print()
print("Максимальный элемент b:", np.max(b)
     )
print("Сумма элементов массива b:", np.sum(b)
     )
print("Индекс максимального элемента b:", np.argmax(b)
     )

Разность между a и b: [-1  1 -3 -3 -2]
Квадраты элементов b: [  4   9  81  25 144]
Половины произведений элементов массивов a и b: [ 1  6 27  5 60]

Максимальный элемент b: 12
Сумма элементов массива b: 31
Индекс максимального элемента b: 4


 Задайте два массива: [5, 2, 3, 12, 4, 5]   и   ['f', 'o', 'o', 'b', 'a', 'r']

Выведите буквы из второго массива, индексы которых соответствуют индексам чисел из первого массива, которые больше 1, меньше 5 и делятся на 2

In [25]:
import numpy as np
a = np.array([5, 2, 3, 12, 4, 5])
b = np.array(['f', 'o', 'o', 'b', 'a', 'r'])
print(b[(a>1)&(a<5)&(a%2==0)])

['o' 'a']
